export const   HOME_BOOKS_REQUEST="HOME_BOOKS_REQUEST";
export const   HOME_BOOKS_SUCCESS="HOME_BOOKS_SUCCESS";
export const   HOME_BOOKS_FAIL="HOME_BOOKS_FAIL";
export const CLEAR_ERRORS="CLEAR_ERRORS";