export const GET_SOLD_BOOKS_REQUEST="GET_SOLD_BOOKS_REQUEST";
export const GET_SOLD_BOOKS_SUCCESS="GET_SOLD_BOOKS_SUCCESS";
export const GET_SOLD_BOOKS_FAIL="GET_SOLD_BOOKS_FAIL";

export const SELL_BOOK_REQUEST="SELL_BOOK_REQUEST";
export const SELL_BOOK_SUCCESS="SELL_BOOK_SUCCESS";
export const SELL_BOOK_FAIL="SELL_BOOK_FAIL";

